#!/bin/bash

# Ensure the PATH is set correctly
# export PATH="$HOME/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

# Debugging statement to print the PATH
echo "PATH is: $PATH"

# Ensure that the necessary commands are available
for cmd in git cut; do
    if ! command -v $cmd &> /dev/null; then
        echo "$cmd could not be found. Please install $cmd."
        exit 1
    fi
done

# List of repositories as: "<dir-name> <remote-url>"
repos=(
  "alacritty https://github.com/alacritty/alacritty.git"
  "Arch-Hyprland https://github.com/JaKooLit/Arch-Hyprland"
  "asm-lsp https://github.com/bergercookie/asm-lsp.git"
  "autotools-language-server https://github.com/Freed-Wu/autotools-language-server.git"
  "awk-language-server https://github.com/Beaglefoot/awk-language-server.git"
  "backup_scripts https://github.com/Epineph/backup_scripts.git"
  "base16-builder-go https://github.com/tinted-theming/base16-builder-go.git"
  "base16-shell https://github.com/chriskempson/base16-shell.git"
  "bash-language-server https://github.com/bash-lsp/bash-language-server.git"
  "bat https://github.com/sharkdp/bat.git"
  "bat-extras https://github.com/eth-p/bat-extras.git"
  "bats-assert https://github.com/bats-core/bats-assert.git"
  "bats-core https://github.com/bats-core/bats-core.git"
  "bats-file https://github.com/bats-core/bats-file.git"
  "bats-mock https://github.com/buildkite-plugins/bats-mock.git"
  "bats-support https://github.com/bats-core/bats-support.git"
  "beautysh https://github.com/lovesegfault/beautysh.git"
  "carapace-bin https://github.com/carapace-sh/carapace-bin.git"
  "cargo-commander https://github.com/simonhyll/cargo-commander.git"
  "chainer-chemistry https://github.com/chainer/chainer-chemistry.git"
  "chembl_webresource_client https://github.com/chembl/chembl_webresource_client.git"
  "ChemFST https://github.com/esrehmki/ChemFST.git"
  "CMake https://github.com/Kitware/CMake.git"
  "course-pharmacokinetic-modelling https://github.com/matthiaskoenig/course-pharmacokinetic-modelling.git"
  "crowbook https://github.com/lise-henry/crowbook.git"
  "delta https://github.com/dandavison/delta.git"
  "direnv https://github.com/direnv/direnv.git"
  "dotbot https://github.com/anishathalye/dotbot.git"
  "doxide https://github.com/lawmurray/doxide.git"
  "doxygen https://github.com/doxygen/doxygen"
  "dracula.nvim https://github.com/Mofiqul/dracula.nvim.git"
  "etc_jupyterlab_nbgrader_validate https://github.com/educational-technology-collective/etc_jupyterlab_nbgrader_validate.git"
  "eza https://github.com/eza-community/eza.git"
  "fancybook https://github.com/drahnr/fancybook.git"
  "fd https://github.com/sharkdp/fd.git"
  "fidget.nvim https://github.com/j-hui/fidget.nvim.git"
  "flavours https://github.com/Misterio77/flavours.git"
  "fzf https://github.com/junegunn/fzf.git"
  "generate_install_command https://github.com/Epineph/generate_install_command"
  "gocc https://github.com/goccmack/gocc.git"
  "html-to-markdown https://github.com/JohannesKaufmann/html-to-markdown.git"
  "htmx-lsp https://github.com/ThePrimeagen/htmx-lsp.git"
  "hydra-lsp https://github.com/Retsediv/hydra-lsp.git"
  "ipyflex https://github.com/trungleduc/ipyflex.git"
  "ipykernel https://github.com/ipython/ipykernel"
  "ipynb-to-md https://github.com/diaakasem/ipynb-to-md.git"
  "ipython https://github.com/ipython/ipython"
  "ipywidgets https://github.com/jupyter-widgets/ipywidgets.git"
  "jrep https://github.com/joshua-laughner/jrep.git"
  "jsoncpp https://github.com/open-source-parsers/jsoncpp.git"
  "jupyter https://github.com/jupyter/jupyter"
  "jupyter_client https://github.com/jupyter/jupyter_client"
  "jupyter_core https://github.com/jupyter/jupyter_core"
  "jupyterlab https://github.com/jupyterlab/jupyterlab"
  "jupyterlab-lsp https://github.com/jupyter-lsp/jupyterlab-lsp.git"
  "jupyterlab_sublime https://github.com/zhangfeiran/jupyterlab_sublime.git"
  "just https://github.com/casey/just.git"
  "langserver https://github.com/nim-lang/langserver.git"
  "lazygit https://github.com/jesseduffield/lazygit.git"
  "libressl-3.9.2 https://github.com/libressl-portable/portable.git"
  "linkify-it https://github.com/markdown-it/linkify-it.git"
  "llvmlite https://github.com/numba/llvmlite.git"
  "lsd https://github.com/lsd-rs/lsd.git"
  "LSP https://github.com/sublimelsp/LSP.git"
  "luau-lsp https://github.com/JohnnyMorganz/luau-lsp.git"
  "magic-wormhole https://github.com/magic-wormhole/magic-wormhole.git"
  "manage_lvm_space https://github.com/Epineph/manage_lvm_space.git"
  "markdown https://github.com/Python-Markdown/markdown.git"
  "markdown-it https://github.com/markdown-it/markdown-it.git"
  "mason.nvim https://github.com/mason-org/mason.nvim.git"
  "mason-registry https://github.com//mason-org/mason-registry.git"
  "MathJax https://github.com/mathjax/MathJax.git"
  "MathJax-demos-node https://github.com/mathjax/MathJax-demos-node.git"
  "MathJax-docs https://github.com/mathjax/MathJax-docs.git"
  "mdBook https://github.com/rust-lang/mdBook.git"
  "mdbook-bash-tutorial https://github.com/filariow/mdbook-bash-tutorial.git"
  "mdbook-epub https://github.com/Michael-F-Bryan/mdbook-epub.git"
  "mdbook-inline-highlighting https://github.com/phoenixr-codes/mdbook-inline-highlighting.git"
  "mdbook-katex https://github.com/lzanini/mdbook-katex.git"
  "mdbook-latex https://github.com/lbeckman314/mdbook-latex.git"
  "mdbook-preprocessor-utils https://github.com/willcrichton/mdbook-preprocessor-utils.git"
  "mdbook-scientific https://github.com/drahnr/mdbook-scientific.git"
  "mdcat https://github.com/swsnr/mdcat.git"
  "mdformat https://github.com/hukkin/mdformat.git"
  "mdformat-ruff https://github.com/Freed-Wu/mdformat-ruff.git"
  "mdformat-shfmt https://github.com/hukkin/mdformat-shfmt.git"
  "mdformat-web https://github.com/hukkin/mdformat-web.git"
  "meson-python https://github.com/mesonbuild/meson-python.git"
  "micromamba-releases https://github.com/mamba-org/micromamba-releases.git"
  "miller https://github.com/johnkerl/miller.git"
  "mkdocs https://github.com/mkdocs/mkdocs.git"
  "MoBi https://github.com/Open-Systems-Pharmacology/MoBi.git"
  "move https://github.com/move-language/move.git"
  "mulle-bashfunctions https://github.com/mulle-nat/mulle-bashfunctions.git"
  "mutt-language-server https://github.com/neomutt/mutt-language-server.git"
  "my_R_config https://github.com/Epineph/my_R_config.git"
  "my_zshrc https://github.com/Epineph/my_zshrc"
  "nbread https://github.com/tnwei/nbread.git"
  "nelua-lsp https://github.com/codehz/nelua-lsp.git"
  "nelua.vim https://github.com/stefanos82/nelua.vim.git"
  "neoformat https://github.com/sbdchd/neoformat.git"
  "networkx https://github.com/networkx/networkx.git"
  "next-ls https://github.com/elixir-tools/next-ls.git"
  "nickel https://github.com/tweag/nickel.git"
  "nil https://github.com/oxalica/nil.git"
  "nimlsp https://github.com/PMunch/nimlsp.git"
  "ninja https://github.com/ninja-build/ninja.git"
  "nomad-lsp https://github.com//juliosueiras/nomad-lsp.git"
  "nteract https://github.com/nteract/nteract.git"
  "numba https://github.com/numba/numba"
  "numd https://github.com/nushell-prophet/numd.git"
  "numpy https://github.com/numpy/numpy.git"
  "NvChad https://github.com/NvChad/NvChad"
  "nvim_conf https://github.com/Epineph/nvim_conf"
  "nvim-dap https://github.com/mfussenegger/nvim-dap.git"
  "nvim-idris2 https://github.com/ShinKage/nvim-idris2.git"
  "nvim-jdtls https://github.com/mfussenegger/nvim-jdtls.git"
  "ocaml https://github.com/ocaml/ocaml"
  "onedrive https://github.com/abraunegg/onedrive.git"
  "oniguruma https://github.com/defuz/oniguruma.git"
  "openbabel https://github.com/openbabel/openbabel.git"
  "openscad-language-server https://github.com/dzhu/openscad-language-server.git"
  "openscad-LSP https://github.com/Leathong/openscad-LSP.git"
  "OSPSuite.Core https://github.com/Open-Systems-Pharmacology/OSPSuite.Core.git"
  "OSPSuite-R https://github.com/Open-Systems-Pharmacology/OSPSuite-R.git"
  "oxc https://github.com/oxc-project/oxc.git"
  "package_control https://github.com/wbond/package_control.git"
  "Packages https://github.com/sublimehq/Packages.git"
  "pandoc https://github.com/jgm/pandoc.git"
  "papaja https://github.com/crsh/papaja.git"
  "paru https://aur.archlinux.org/paru.git"
  "pascal-language-server https://github.com/genericptr/pascal-language-server.git"
  "PerlNavigator https://github.com/bscan/PerlNavigator.git"
  "persist https://github.com/visdesignlab/persist.git"
  "pest-ide-tools https://github.com/pest-parser/pest-ide-tools.git"
  "phan https://github.com/phan/phan.git"
  "pharmsol https://github.com/LAPKB/pharmsol.git"
  "phpactor https://github.com/phpactor/phpactor.git"
  "PK-Py https://github.com/peytoncchen/PK-Py.git"
  "PK-Sim https://github.com/Open-Systems-Pharmacology/PK-Sim.git"
  "plotpy https://github.com/cpmech/plotpy.git"
  "prettier https://github.com/prettier/prettier.git"
  "processing-sublime https://github.com/b-g/processing-sublime.git"
  "python-lsp-black https://github.com/python-lsp/python-lsp-black.git"
  "qtconsole https://github.com/jupyter/qtconsole"
  "quarto-cli https://github.com/quarto-dev/quarto-cli.git"
  "rdkit https://github.com/rdkit/rdkit.git"
  "re2c https://github.com/skvadrik/re2c.git"
  "redshift https://github.com/jonls/redshift.git"
  "rhash https://github.com/rhash/RHash.git"
  "rich https://github.com/Textualize/rich.git"
  "rich-cli https://github.com/Textualize/rich-cli.git"
  "ripgrep https://github.com/BurntSushi/ripgrep.git"
  "rmarkdown https://github.com/rstudio/rmarkdown.git"
  "rocks.nvim https://github.com/nvim-neorocks/rocks.nvim.git"
  "rust-csv https://github.com/BurntSushi/rust-csv.git"
  "ryacas https://github.com/r-cas/ryacas.git"
  "ScaffoldGraph https://github.com/UCLCheminformatics/ScaffoldGraph.git"
  "schemes https://github.com/tinted-theming/schemes.git"
  "SeleniumBase https://github.com/seleniumbase/SeleniumBase.git"
  "semver https://github.com/semver/semver.git"
  "ShaderLang https://github.com/NazaraEngine/ShaderLang.git"
  "shiny-examples https://github.com/rstudio/shiny-examples.git"
  "sh-to-markdown https://github.com/rreinold/sh-to-markdown.git"
  "slather https://github.com/SlatherOrg/slather.git"
  "sphinx https://github.com/sphinx-doc/sphinx.git"
  "starship https://github.com/starship/starship.git"
  "sublime https://github.com/JaredCubilla/sublime.git"
  "SublimeAllAutocomplete https://github.com/alienhard/SublimeAllAutocomplete.git"
  "sublime-bats https://github.com/sptndc/sublime-bats.git"
  "swig https://github.com/swig/swig.git"
  "syntect https://github.com/trishume/syntect.git"
  "terminado https://github.com/jupyter/terminado"
  "thesisdown https://github.com/ismayc/thesisdown.git"
  "thorium-browser-bin https://aur.archlinux.org/thorium-browser-bin.git"
  "tinted-shell https://github.com/tinted-theming/tinted-shell.git"
  "tinty https://github.com/tinted-theming/tinty.git"
  "tinytex https://github.com/yihui/tinytex.git"
  "tree-sitter-phpdoc https://github.com/claytonrcarter/tree-sitter-phpdoc.git"
  "useful-scripts https://github.com/hoelzro/useful-scripts.git"
  "UserScripts https://github.com/Epineph/UserScripts.git"
  "vcpkg https://github.com/microsoft/vcpkg.git"
  "vdplus https://github.com/visidata/vdplus.git"
  "vim-lsp https://github.com/prabirshrestha/vim-lsp.git"
  "visidata https://github.com/saulpw/visidata.git"
  "visual-studio-code-bin https://aur.archlinux.org/visual-studio-code-bin.git"
  "WoeUSB-ng https://github.com/WoeUSB/WoeUSB-ng.git"
  "xcbuild https://github.com/facebook/xcbuild.git"
  "xsv https://github.com/BurntSushi/xsv.git"
  "yay https://aur.archlinux.org/yay.git"
  "zfsArch https://github.com/Epineph/zfsArch.git"
  "zoxide https://github.com/ajeetdsouza/zoxide.git"
)


# Directory to store repositories
repo_dir="/home/heini/repos/"
mkdir -p "$repo_dir"

# Check and clone repositories if they do not exist
for repo in "${repos[@]}"; do
    name=$(echo $repo | cut -d ' ' -f 1)
    url=$(echo $repo | cut -d ' ' -f 2)
    path="$repo_dir/$name"

    if [ ! -d "$path" ]; then
        echo "Cloning $name from $url..."
        git clone --recurse-submodules "$url" "$path"
    else
        echo "$name already exists at $path."
    fi
done
