#!/usr/bin/env bash
sudo refresh-mirrors
yay -Syyy
gen_log yay -S --needed python-dnspython python-jmespath python-jschema-to-python python-junit-xml python-netaddr python-passlib python-pip python-pywinrm python-sarif-om python-setuptools python-systemd sshpass oh-my-update python-netifaces python-psutil python-pygit2 vim-powerline which clang entr exa fzf git-delta prettier python-black shfmt mypy pyright python-eradicate python-pip python-psutil python-pylint python-pyroma python-ruff python-setuptools python-sphinx python-tomli python-yaml vulture bandit flake8 mypy pylama python-black python-pep8 python-prospector python-pydocstyle python-pylint pytype yapf
gen_log yay -S --needed fd neovim-tree-sitter ripgrep vim-devicons coffeescript gcc gcc-ada ghc go java-environment-openjdk julia jupyter lua python3 r ruby scala python-cmarkgfm python-lockfile python-pyaml python-pyicu python-ruamel-yaml qemu-block-dmg qemu-block-gluster qemu-block-iscsi qemu-block-nfs qemu-block-ssh qemu-chardev-baum qemu-chardev-spice qemu-desktop qemu-docs qemu-emulators-full qemu-full qemu-hw-display-qxl qemu-hw-display-virtio-gpu
gen_log yay -S --needed qemu-hw-display-virtio-gpu-gl qemu-hw-display-virtio-gpu-pci qemu-hw-display-virtio-gpu-pci-gl qemu-hw-display-virtio-gpu-pci-rutabaga qemu-hw-display-virtio-gpu-rutabaga qemu-hw-display-virtio-vga qemu-hw-display-virtio-vga-gl qemu-hw-display-virtio-vga-rutabaga qemu-hw-s390x-virtio-gpu-ccw qemu-hw-uefi-vars qemu-hw-usb-host qemu-hw-usb-redirect qemu-hw-usb-smartcard qemu-pr-helper qemu-system-aarch64 qemu-system-alpha qemu-system-arm qemu-system-avr qemu-system-hppa qemu-system-m68k qemu-system-microblaze qemu-system-mips qemu-system-or1k qemu-system-ppc qemu-system-riscv qemu-system-rx qemu-system-s390x qemu-system-sh4 qemu-system-sparc qemu-system-tricore qemu-system-xtensa qemu-tests qemu-tools qemu-ui-curses qemu-ui-dbus qemu-ui-egl-headless qemu-ui-gtk qemu-ui-opengl qemu-ui-sdl qemu-ui-spice-app qemu-ui-spice-core qemu-user qemu-vhost-user-gpu qemu-vmsr-helper samba sbsigntools sdl-1 texlive-latexrecommended wdiff
gen_log yay -S --needed perl postgresql-old-upgrade python python-click python-curio python-dateutil python-defusedxml python-django python-dnspython-1 python-dpcontracts python-faker python-gssapi python-idna python-lark-parser python-libcst python-lxml python-numpy python-pandas python-pyasn1 ripgrep vim-devicons coffeescript gcc gcc-ada ghc go java-environment-openjdk julia jupyter lua python3 r ruby scala python-cmarkgfm python-lockfile python-pyaml python-pyicu python-ruamel-yaml qemu-block-dmg qemu-block-gluster qemu-block-iscsi qemu-block-nfs qemu-block-ssh qemu-chardev-baum qemu-chardev-spice qemu-desktop qemu-docs qemu-emulators-full qemu-full qemu-hw-display-qxl qemu-hw-display-virtio-gpu qemu-hw-display-virtio-gpu-gl qemu-hw-display-virtio-gpu-pci qemu-hw-display-virtio-gpu-pci-gl qemu-hw-display-virtio-gpu-pci-rutabaga qemu-hw-display-virtio-gpu-rutabaga qemu-hw-display-virtio-vga qemu-hw-display-virtio-vga-gl qemu-hw-display-virtio-vga-rutabaga qemu-hw-s390x-virtio-gpu-ccw qemu-hw-uefi-vars qemu-hw-usb-host qemu-hw-usb-redirect qemu-hw-usb-smartcard qemu-pr-helper qemu-system-aarch64 qemu-system-alpha qemu-system-arm qemu-system-avr qemu-system-hppa qemu-system-m68k qemu-system-microblaze qemu-system-mips qemu-system-or1k qemu-system-ppc qemu-system-riscv qemu-system-rx qemu-system-s390x qemu-system-sh4 qemu-system-sparc qemu-system-tricore qemu-system-xtensa qemu-tests qemu-tools qemu-ui-curses qemu-ui-dbus qemu-ui-egl-headless qemu-ui-gtk qemu-ui-opengl qemu-ui-sdl qemu-ui-spice-app qemu-ui-spice-core qemu-user qemu-vhost-user-gpu qemu-vmsr-helper samba sbsigntools sdl-1 texlive-latexrecommended wdiff
gen_log yay -S --needed perl postgresql-old-upgrade python python-click python-curio python-dateutil python-defusedxml python-django python-dnspython-1 python-dpcontracts python-faker python-gssapi python-idna python-lark-parser python-libcst python-lxml python-numpy python-pandas python-pyasn1 python-pytest python-pytz python-redis python-requests-toolbelt python-rich python-sniffio python-trio python-watchdog python-xcffib tcl
gen_log yay -S --needed glow gzip highlight imagemagick jpegexiforient-1 jq kimageformats less lha libappimage libarchive libsixel lynx lzop mdcat mdless mediainfo mpv odt2txt openexr p7zip pandoc perl perl-image-exiftool perl-xls2csv phonon-qt6 plasma-activities-stats poppler python python-pdftotext python-xlsx2csv qt6-imageformats source-highlight stat strings taglib tar tmux transmission-cli ueberzug unace unrar unrtf unzip viu w3m xz yt-dlp zip zsh python-cryptography python-markdown opus-tools pavucontrol python-pyqt5 python-soco sox vorbis-tools youtube-dl
gen_log yay -S --needed glew hdf5 java-hamcrest java-runtime opencl-icd-loader qt6-base vtk lua52-yaml lua53-yaml lua-yaml gtk-vnc kwallet5 libsecret libvncserver spice-gtk webkit2gtk-4.1 python-ipykernel r sagemath-jupyter btrfs-progs cni-plugins cockpit-machines cockpit-packagekit fuse-overlayfs gtk4 java-runtime java-runtime-headless networkmanager nomad-driver-containerd nomad-driver-lxc nomad-driver-nspawn nomad-driver-podman
gen_log yay -S --needed pcp perl-date-parse pipewire podman-compose podman-docker polkit python-openpyxl qemu qt5-base slirp4netns sscg sssd sudo trash-cli xdg-utils bdsup2subpp context mkclean mkvalidator noto-fonts-emoji python-nautilus qtesseract5 ttf-nerd-fonts-symbols-mono languagetool okular rga clang mulle-semver
gen_log yay -S --needed kwindowsystem libass libavc1394 libbluray libcaca libdc1394 libdvdnav libdvdread libgme libgoom2 libjpeg-turbo libkate libmicrodns libmodplug libmtp libnfs libnotify libogg libpng libpulse librsvg libsamplerate libshout libsoxr libssh2 libtheora libtiger libva-intel-driver libva-vdpau-driver libvorbis libvpx libxkbcommon lirc live-media lua-socket mpg123 opus pcsclite projectm protobuf smbclient speex srt systemd-libs twolame zvbi aom aribb25 avahi dav1d flac fluidsynth gst-plugins-base-libs gtk3 lua-sec mercurial
gen_log yay -S context curl graphicsmagick inkscape lua51-filesystem lua51-linenoise lua51-yaml luarocks noto-fonts-cjk pstoedit ttf-hack zint --needed
gen_log yay -S --needed libogg libpng lirc aribb25 avahi cmake dav1d flac fluidsynth git glib2 kwallet libass libavc1394 libbluray libcaca libcdio libdc1394 libdvdcss libdvdnav libdvdread libgme libgoom2 libjpeg-turbo libkate libmicrodns libmodplug libmtp libnfs libnl libnotify libogg libpn libraw1394 librsvg libsamplerate libshout libsoxr libssh2 libtheora libtiger libudev.so libvorbis libvpx libx11 live-media lua51-luautf8 lua-sec mercurial mpg123 ncurses opus pcsclite projectm protobuf sdl12-compat sdl_image smbclient speex speexdsp srt systemd-libs ttf-dejavu twolame vcdimager x264 x265 xcb-util >=3.0
gen_log yay -S --needed python-botocore python-bson python-itsdangerous python-pymongo python-redis python-ujson python-yaml gtk2 gtk3 libx11 mc nftables python qt5-base qt5-x11extras python-hiredis python-pyopenssl python-requests libappindicator-gtk3 python-aiohttp-socks python-babel python-emoji python-motor python-rapidjson python-redis python-ujson xdg-utils pyside6 python-django python-flask python-pickleshare python-pycares python-pyqt5-webengine python-pyqt6 python-pyqt6-webengine python-redis python-twisted yapf

yay -Syyu --noconfirm
sudo mkinitcpio -P
sudo grub-mkconfig -o /boot/grub/grub.cfg
