#!/usr/bin/env bash

sudo refresh-mirrors
yay -Syyy
sudo pacman-key --init
sudo pacman-key --populate archlinux
sudo pacman-key --refresh-keys
sudo pacman-key --init
sudo pacman-key --populate archlinux
yay -Syyy

gen_log yay -S --needed texlive-xetex tectonic typst python-weasyprint texlive-context cross-references pandoc-crossref python-trio python-curio python-requests-toolbelt openexr libraw jxrlib jpegexiforient mcpp luametatex ttf-linux-libertine otf-libertinus csvlook csvtable strings stat ffmpeg unrar less mdcat mdless chafa catimg transmission-cli perl-image-exiftool unrtf catdoc antiword odt2txt lynx highlight source-highlight elinks atool mlocate fasd ctags fd perl-xls2csv
gen_log yay -S --needed python-xlsx2csv python-pdftotext perl-image-exiftool exa geoip2-database aspell kio-fuse kio-extras pkcs11-helper botan kwalletmanager pyside6 vkbasalt mesa-utils gamescope cpio lha unace perl-archive-zip perl-io-compress-brotli c-xsc cddlib curl fplll libmpc libsemigroups libxaw mpfi nauty normaliz pari planarity polymake python-outcome python-pytest python-uvloop singular zeromq alsa-lib appstream avahi curl dav1d db dhcpcd diffutils dnsmasq e2fsprogs efibootmgr exo ffmpeg fftw firewalld bash-completion openexr libraw jxrlib
gen_log yay -S --needed jpegexiforient mcpp luametatex ttf-linux-libertine otf-libertinus csvlook csvtable strings stat ffmpeg unrar less mdcat mdless chafa catimg transmission-cli perl-image-exiftool unrtf catdoc antiword odt2txt lynx highlight source-highlight elinks atool mlocate fasd ctags fd perl-xls2csv python-xlsx2csv python-pdftotext perl-image-exiftool exa geoip2-database aspell kio-fuse kio-extras pkcs11-helper botan kwalletmanager pyside6 vkbasalt mesa-utils gamescope cpio lha unace perl-archive-zip perl-io-compress-brotli c-xsc cddlib curl fplll libmpc libsemigroups libxaw mpfi nauty normaliz pari planarity polymake python-outcome python-pytest python-uvloop singular zeromq alsa-lib appstream avahi curl dav1d
gen_log yay -S --needed db dhcpcd diffutils dnsmasq e2fsprogs efibootmgr exo ffmpeg fftw firewalld bash-completion swi-prolog python-pyqt6 curl dav1d db dhcpcd diffutils dnsmasq e2fsprogs efibootmgr exo ffmpeg fftw firewalld fluidsynth freetds freetype2 frei0r-plugins fuse3 gcc-fortran gdk-pixbuf2 ghostscript glib2-devel glibc glu gnupg gnutls graphite
gen_log yay -S --needed gtk-update-icon-cache guile gvfs iio-sensor-proxy imagemagick java-environment java-runtime kguiaddons kwallet5 kwayland5 kwindowsystem ladspa less libarchive libavif libbpf libcups libdecor libevent libfbclient libffado libfido2 libgit2 libheif libisoburn libjxl libldap libmysofa libopenraw libp11-kit libpng
gen_log yay -S --needed libpwquality librsvg libsecret libvoikko libxau libxaw libxml2 memcached mercurial modemmanager mtools nftables nss openssl openucc org.freedesktop.secrets os-prober pacrunner pam pango pcmanfm perl perl-authen-sasl perl-cgi perl-datetime-format-builder perl-datetime-format-iso8601 perl-file-homedir perl-file-mimeinfo perl-io-socket-ssl perl-libwww perl-locale-gettext
gen_log yay -S --needed perl-lwp-protocol-https reshade-shaders-git icoutils perl-mediawiki-api perl-net-dbus perl-term-readkey perl-tk perl-x11-protocol pipewire polkit postgresql postgresql-libs ppp prrte-docs psutils pyside6 python python-beautifulsoup4
gen_log yay -S --needed python-cairocffi python-certifi python-cffi python-colorama python-cryptography python-dbus python-defusedxml python-dotenv python-email-validator python-fs python-fsspec python-genshi python-gobject python-gpgme python-h2 python-html5lib python-hypothesis python-idna python-jinja
gen_log yay -S --needed python-libevdev python-linkify-it-py python-lxml python-lz4 python-matplotlib python-merge3 python-numba python-numexpr python-numpy python-olefile python-openpyxl python-paramiko python-pip python-pipx python-psutil python-pyarrow python-pycocotools python-pydot python-pyelftools python-pygments python-pygraphviz python-pyinotify python-pyjwt python-pymysql python-pyopenssl python-pyqt5 python-pyqt6 python-pysocks python-pytables python-pyu2f python-pyudev python-pyyaml python-qtpy python-reportlab python-requests python-scikit-learn python-scipy python-setuptools python-snappy python-sqlalchemy python-symengine python-sympy python-tabulate python-tornado python-tqdm python-twisted python-unicodedata2
gen_log yay -S --needed python-wxpython python-xarray python-xdg python-xlrd python-xlsxwriter python-xlwt python-yaml python-zopfli python-zstandard qemu-desktop qrencode qt5-base qt5-declarative qt5-wayland qt5-x11extras qt6-5compat qt6-base qt6-declarative qt6-quick3d qt6-serialport qt6-shadertools qt6-wayland quota-tools r rav1e realtime-privileges ruby ruby-bundled-gems ruby-default-gems
gen_log yay -S --needed subversion sudo svt-av1 systemd-sysvcompat systemd-ukify tcl texlive-binextra texlive-fontsrecommended texlive-latexrecommended tk tpm2-tss unixodbc util-linux valkey vpl-gpu-rt vulkan-driver wayland webp-pixbuf-loader wireless-regdb wl-clipboard x11-ssh-askpass xclip xorg-server xorg-server-devel xorg-xauth xsel xterm xz zlib ruby-docs ruby-stdlib scx-scheds sdl sh smtp-forwarder sndio speech-dispatcher spirv-tools
gen_log yay -S --needed luametatex ttf-linux-libertine otf-libertinus csvlook csvtable strings stat ffmpeg unrar less mdcat mdless chafa catimg transmission-cli perl-image-exiftool unrtf catdoc antiword odt2txt lynx highlight source-highlight elinks atool mlocate fasd ctags fd perl-xls2csv python-xlsx2csv python-pdftotext perl-image-exiftool exa geoip2-database aspell kio-fuse kio-extras pkcs11-helper botan kwalletmanager pyside6
gen_log yay -S --needed sratom zix sord serd sbc lv2 lua libldac python-rdflib python-lxml lv2-example-plugins lv2-docs python-beautifulsoup4 python-cssselect python-lxml-docs jdk-openjdk libjpeg libxft libxinerama libxpm python unixodbc dialog java-runtime perl-file-homedir perl-ipc-system-simple perl-tk perl-yaml-tiny python sbsigntools texlive-latexrecommended wdiff python-lxml-html-clean python-lilv gtk2 gtk4 webkit2gtk-4.1
gen_log yay -S --needed gcc-fortran python-bottleneck python-cftime python-dask python-distributed python-matplotlib python-pint python-scipy python-seaborn python-wxpython gcc-fortran python-bottleneck python-cftime python-dask python-distributed python-matplotlib python-pint python-scipy python-seaborn python-wxpython qemu-audio-alsa qemu-audio-dbus qemu-audio-jack qemu-audio-oss qemu-audio-pa qemu-audio-pipewire qemu-audio-sdl qemu-audio-spice qemu-block-curl qemu-block-dmg qemu-block-gluster qemu-block-iscsi qemu-block-nfs qemu-block-ssh qemu-chardev-baum qemu-chardev-spice qemu-desktop qemu-docs qemu-emulators-full qemu-full qemu-hw-display-qxl
gen_log yay -S --needed qemu-hw-display-virtio-gpu qemu-hw-display-virtio-gpu-gl qemu-hw-display-virtio-gpu-pci qemu-hw-display-virtio-gpu-pci-gl qemu-hw-display-virtio-gpu-pci-rutabaga qemu-hw-display-virtio-gpu-rutabaga qemu-hw-display-virtio-vga qemu-hw-display-virtio-vga-gl qemu-hw-display-virtio-vga-rutabaga qemu-hw-s390x-virtio-gpu-ccw qemu-hw-uefi-vars qemu-hw-usb-host qemu-hw-usb-redirect qemu-hw-usb-smartcard qemu-pr-helper qemu-system-aarch64 qemu-system-alpha qemu-system-arm qemu-system-avr qemu-system-hppa qemu-system-m68k qemu-system-microblaze qemu-system-mips qemu-system-or1k qemu-system-ppc qemu-system-riscv qemu-system-rx qemu-system-s390x qemu-system-sh4 qemu-system-sparc qemu-system-tricore qemu-system-xtensa qemu-tests qemu-tools qemu-ui-curses qemu-ui-dbus qemu-ui-egl-headless qemu-ui-gtk qemu-ui-opengl qemu-ui-sdl qemu-ui-spice-app qemu-ui-spice-core qemu-user qemu-vhost-user-gpu qemu-vmsr-helper quota-tools samba texlive-latex dbus-python pyside6
gen_log yay -S --needed python-appdirs python-bcrypt python-cryptography python-dbus python-fsspec python-gobject python-h2 python-idna python-lz4 python-pandas python-priority python-pyasn1 python-pynacl python-pyopenssl python-pyqt5-webengine python-pyqt6 python-pyqt6-webengine python-pyserial python-service-identity python-twisted python-wcwidth python-wxpython qt5-connectivity qt5-declarative qt5-location qt5-multimedia qt5-quick3d qt5-remoteobjects qt5-sensors qt5-serialport qt5-speech qt5-svg qt5-tools qt5-webchannel qt5-websockets qt5-x11extras qt5-xmlpatterns qt6-connectivity qt6-declarative qt6-multimedia qt6-positioning qt6-quick3d qt6-remoteobjects qt6-scxml qt6-sensors qt6-serialport qt6-speech qt6-svg qt6-webchannel qt6-webengine qt6-websockets tk
gen_log yay -S --needed perl postgresql-old-upgrade python python-click python-dateutil python-defusedxml python-distributed python-django python-dpcontracts python-faker python-gssapi python-lark-parser python-libarchive-c python-libcst python-lxml python-lz4 python-numpy python-pandas python-paramiko python-pyarrow python-pyasn1 python-pygit2 python-pytest python-pytz python-redis python-requests python-rich python-smbprotocol python-snappy python-tqdm python-watchdog python-xcffib python-zstandard tcl git
gen_log yay -S --needed libnotify python-aiohttp python-awesomeversion python-better-exceptions python-gobject python-httpx python-jq python-lxml python-packaging python-pycares python-rich python-toml python-twisted libgcrypt libsasl openssl pkcs11-helper biber gavl libmpcdec python qt5-x11extras rtmpdump xorg-mkfontscale cddlib context gtk3 libnotify networkmanager pari-elldata pari-galdata pari-galpol pari-seadata perl-io-compress-brotli polkit python-pyqt6
gen_log yay -S --needed texlive-xetex tectonic typst python-weasyprint texlive-context cross-references pandoc-crossref python-trio python-curio python-requests-toolbelt openexr libraw jxrlib jpegexiforient mcpp luametatex ttf-linux-libertine otf-libertinus csvlook csvtable strings stat ffmpeg unrar less mdcat mdless chafa catimg transmission-cli perl-image-exiftool unrtf catdoc antiword odt2txt lynx highlight source-highlight elinks atool mlocate fasd ctags fd perl-xls2csv python-xlsx2csv python-pdftotext perl-image-exiftool exa geoip2-database aspell kio-fuse kio-extras pkcs11-helper botan kwalletmanager pyside6 vkbasalt mesa-utils gamescope cpio lha unace perl-archive-zip perl-io-compress-brotli c-xsc cddlib curl fplll libmpc libsemigroups libxaw mpfi nauty normaliz pari planarity polymake python-outcome python-pytest python-uvloop singular zeromq alsa-lib appstream avahi curl dav1d db dhcpcd diffutils dnsmasq e2fsprogs efibootmgr exo ffmpeg fftw firewalld bash-completion swi-prolog python-pyqt6

yay -Syyy
yay -Syyu --noconfirm
sudo mkinitcpio -P
sudo grub-mkconfig -o /boot/grub/grub.cfg
sudo reboot now
