choco uninstall nerdfont-hack -y
choco uninstall nerd-fonts-0xProto -y
choco uninstall nerd-fonts-3270 -y
choco uninstall nerd-fonts-Agave -y
choco uninstall nerd-fonts-AnonymousPro -y
choco uninstall nerd-fonts-Arimo -y
choco uninstall nerd-fonts-AurulentSansMono -y
choco uninstall nerd-fonts-BigBlueTerminal -y
choco uninstall nerd-fonts-BitstreamVeraSansMono -y
choco uninstall nerd-fonts-CascadiaCode -y
choco uninstall nerd-fonts-CascadiaMono -y
choco uninstall nerd-fonts-CodeNewRoman -y
choco uninstall nerd-fonts-ComicShannsMono -y
choco uninstall nerd-fonts-CommitMono -y
choco uninstall nerd-fonts-Cousine -y
choco uninstall nerd-fonts-D2Coding -y
choco uninstall nerd-fonts-DaddyTimeMono -y
choco uninstall nerd-fonts-DejaVuSansMono -y
choco uninstall nerd-fonts-DelugiaBook -y
choco uninstall nerd-fonts-DelugiaComplete -y
choco uninstall nerd-fonts-DelugiaMono-Complete -y
choco uninstall nerd-fonts-DelugiaMono-Powerline -y
choco uninstall nerd-fonts-DelugiaPowerline -y
choco uninstall nerd-fonts-DroidSansMono -y
choco uninstall nerd-fonts-EnvyCodeR -y
choco uninstall nerd-fonts-FantasqueSansMono -y
choco uninstall nerd-fonts-FiraCode -y
choco uninstall nerd-fonts-FiraMono -y
choco uninstall nerd-fonts-GeistMono -y
choco uninstall nerd-fonts-Gohu -y
choco uninstall nerd-fonts-Go-Mono -y
choco uninstall nerd-fonts-Hack -y
choco uninstall nerd-fonts-Hasklig -y
choco uninstall nerd-fonts-HeavyData -y
choco uninstall nerd-fonts-Hermit -y
choco uninstall nerd-fonts-iA-Writer -y
choco uninstall nerd-fonts-IBMPlexMono -y
choco uninstall nerd-fonts-Inconsolata -y
choco uninstall nerd-fonts-InconsolataGo -y
choco uninstall nerd-fonts-InconsolataLGC -y
choco uninstall nerd-fonts-IntelOneMono -y
choco uninstall nerd-fonts-Iosevka -y
choco uninstall nerd-fonts-IosevkaTerm -y
choco uninstall nerd-fonts-IosevkaTermSlab -y
choco uninstall nerd-fonts-JetBrainsMono -y
choco uninstall nerd-fonts-Lekton -y
choco uninstall nerd-fonts-LiberationMono -y
choco uninstall nerd-fonts-Lilex -y
choco uninstall nerd-fonts-MartianMono -y
choco uninstall nerd-fonts-Meslo -y
choco uninstall nerd-fonts-Monaspace -y
choco uninstall nerd-fonts-Monofur -y
choco uninstall nerd-fonts-Monoid -y
choco uninstall nerd-fonts-Mononoki -y
choco uninstall nerd-fonts-MPlus -y
choco uninstall nerd-fonts-NerdFontsSymbolsOnly -y
choco uninstall nerd-fonts-Noto -y
choco uninstall nerd-fonts-OpenDyslexic -y
choco uninstall nerd-fonts-Overpass -y
choco uninstall nerd-fonts-ProFont -y
choco uninstall nerd-fonts-ProggyClean -y
choco uninstall nerd-fonts-Recursive -y
choco uninstall nerd-fonts-RobotoMono -y
choco uninstall nerd-fonts-ShareTechMono -y
choco uninstall nerd-fonts-SourceCodePro -y
choco uninstall nerd-fonts-SpaceMono -y
choco uninstall nerd-fonts-Terminus -y
choco uninstall nerd-fonts-Tinos -y
choco uninstall nerd-fonts-Ubuntu -y
choco uninstall nerd-fonts-UbuntuMono -y
choco uninstall nerd-fonts-UbuntuSans -y
choco uninstall nerd-fonts-VictorMono -y
choco uninstall nerd-fonts-ZedMono -y