#!/bin/bash

# Update and install necessary packages
echo "Updating system and installing necessary packages..."
sudo pacman -Syu --noconfirm
sudo pacman -S --noconfirm networkmanager dnsutils iproute2

# Enable and start NetworkManager
echo "Enabling and starting NetworkManager..."
sudo systemctl enable NetworkManager
sudo systemctl start NetworkManager

# Set up DNS configuration
echo "Setting up DNS configuration..."

# Backup existing resolv.conf
if [ -f /etc/resolv.conf ]; then
    sudo cp /etc/resolv.conf /etc/resolv.conf.bak
    echo "Backup of /etc/resolv.conf created as /etc/resolv.conf.bak"
fi

# Clear the existing resolv.conf
sudo rm -f /etc/resolv.conf

# Create a new resolv.conf
sudo bash -c 'cat <<EOT > /etc/resolv.conf
# Generated by Arch Linux Network Configuration Script
nameserver 1.1.1.1  # Cloudflare DNS
nameserver 8.8.8.8  # Google DNS
nameserver 9.9.9.9  # Quad9 DNS
options edns0
EOT'

# Make resolv.conf immutable to prevent overwriting by network managers
sudo chattr +i /etc/resolv.conf

echo "DNS configuration completed. /etc/resolv.conf set with Cloudflare, Google, and Quad9 DNS servers."

# Optimize network settings for performance and reliability
echo "Optimizing network settings..."

# Disable IPv6 (Optional)
# Uncomment the following lines if you want to disable IPv6
# echo "Disabling IPv6..."
# sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
# sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
# sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1
# echo "net.ipv6.conf.all.disable_ipv6 = 1" | sudo tee -a /etc/sysctl.conf
# echo "net.ipv6.conf.default.disable_ipv6 = 1" | sudo tee -a /etc/sysctl.conf
# echo "net.ipv6.conf.lo.disable_ipv6 = 1" | sudo tee -a /etc/sysctl.conf

# Increase TCP max buffer size and window scaling for better performance
echo "Increasing TCP buffer size and enabling TCP window scaling..."
sudo sysctl -w net.core.rmem_max=16777216
sudo sysctl -w net.core.wmem_max=16777216
sudo sysctl -w net.ipv4.tcp_rmem="4096 87380 16777216"
sudo sysctl -w net.ipv4.tcp_wmem="4096 65536 16777216"
sudo sysctl -w net.ipv4.tcp_window_scaling=1
echo "net.core.rmem_max = 16777216" | sudo tee -a /etc/sysctl.conf
echo "net.core.wmem_max = 16777216" | sudo tee -a /etc/sysctl.conf
echo "net.ipv4.tcp_rmem = 4096 87380 16777216" | sudo tee -a /etc/sysctl.conf
echo "net.ipv4.tcp_wmem = 4096 65536 16777216" | sudo tee -a /etc/sysctl.conf
echo "net.ipv4.tcp_window_scaling = 1" | sudo tee -a /etc/sysctl.conf

# Apply the changes
echo "Applying changes..."
sudo sysctl -p

# Final message
echo "Network configuration complete. NetworkManager is enabled, DNS is configured, and performance optimizations are applied."
echo "You may need to reboot your system for all changes to take effect."

