#!/bin/bash

# Ensure the PATH is set correctly
# export PATH="$HOME/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

# Debugging statement to print the PATH
echo "PATH is: $PATH"

# Ensure that the necessary commands are available
for cmd in git cut; do
    if ! command -v $cmd &> /dev/null; then
        echo "$cmd could not be found. Please install $cmd."
        exit 1
    fi
done
repos=(
    "pandoc https://github.com/jgm/pandoc.git"
    "llvmlite https://github.com/numba/llvmlite.git"
    "mdbook-bash-tutorial https://github.com/filariow/mdbook-bash-tutorial.git"
    "syntect https://github.com/trishume/syntect.git"
    "manage_lvm_space https://github.com/Epineph/manage_lvm_space.git"
    "mdformat-web https://github.com/hukkin/mdformat-web.git"
    "langserver https://github.com/nim-lang/langserver.git"
    "ripgrep https://github.com/BurntSushi/ripgrep.git"
    "nomad-lsp https://github.com//juliosueiras/nomad-lsp.git"
    "oniguruma https://github.com/defuz/oniguruma.git"
    "jupyter https://github.com/jupyter/jupyter.git"
    "SeleniumBase https://github.com/seleniumbase/SeleniumBase.git"
    "micromamba-releases https://github.com/mamba-org/micromamba-releases.git"
    "OSPSuite.Core https://github.com/Open-Systems-Pharmacology/OSPSuite.Core.git"
    "phpactor https://github.com/phpactor/phpactor.git"
    "mason.nvim https://github.com/mason-org/mason.nvim.git"
    "mdformat-shfmt https://github.com/hukkin/mdformat-shfmt.git"
    "just https://github.com/casey/just.git"
    "thesisdown https://github.com/ismayc/thesisdown.git"
    "meson-python https://github.com/mesonbuild/meson-python.git"
    "PK-Sim https://github.com/Open-Systems-Pharmacology/PK-Sim.git"
    "ChemFST https://github.com/esrehmki/ChemFST.git"
    "doxide https://github.com/lawmurray/doxide.git"
    "persist https://github.com/visdesignlab/persist.git"
    "UserScripts https://github.com/Epineph/UserScripts.git"
    "course-pharmacokinetic-modelling https://github.com/matthiaskoenig/course-pharmacokinetic-modelling.git"
    "tinty https://github.com/tinted-theming/tinty.git"
    "nbread https://github.com/tnwei/nbread.git"
    "onedrive https://github.com/abraunegg/onedrive.git"
    "rdkit-pypi https://github.com/kuelumbus/rdkit-pypi.git"
    "ShaderLang https://github.com/NazaraEngine/ShaderLang.git"
    "fzf https://github.com/junegunn/fzf.git"
    "cargo-commander https://github.com/simonhyll/cargo-commander.git"
    "xsv https://github.com/BurntSushi/xsv.git"
    "shiny-examples https://github.com/rstudio/shiny-examples.git"
    "mdformat https://github.com/hukkin/mdformat.git"
    "mkdocs https://github.com/mkdocs/mkdocs.git"
    "ScaffoldGraph https://github.com/UCLCheminformatics/ScaffoldGraph.git"
    "mdbook-scientific https://github.com/drahnr/mdbook-scientific.git"
    "cargo-fuzz https://github.com/rust-fuzz/cargo-fuzz.git"
    "jupyterlab https://github.com/jupyterlab/jupyterlab.git"
    "ocaml https://github.com/ocaml/ocaml.git"
    "eza https://github.com/eza-community/eza.git"
    "LSP https://github.com/sublimelsp/LSP.git"
    "bats-assert https://github.com/bats-core/bats-assert.git"
    "nelua-lsp https://github.com/codehz/nelua-lsp.git"
    "mdbook-inline-highlighting https://github.com/phoenixr-codes/mdbook-inline-highlighting.git"
    "terminado https://github.com/jupyter/terminado.git"
    "dotbot https://github.com/anishathalye/dotbot.git"
    "MathJax https://github.com/mathjax/MathJax.git"
    "starship https://github.com/starship/starship.git"
    "useful-scripts https://github.com/hoelzro/useful-scripts.git"
    "neoformat https://github.com/sbdchd/neoformat.git"
    "mdformat-ruff https://github.com/Freed-Wu/mdformat-ruff.git"
    "redshift https://github.com/jonls/redshift.git"
    "phan https://github.com/phan/phan.git"
    "mdbook-epub https://github.com/Michael-F-Bryan/mdbook-epub.git"
    "html-to-markdown https://github.com/JohannesKaufmann/html-to-markdown.git"
    "nil https://github.com/oxalica/nil.git"
    "jrep https://github.com/joshua-laughner/jrep.git"
    "chembl_webresource_client https://github.com/chembl/chembl_webresource_client.git"
    "numba https://github.com/numba/numba.git"
    "rocks.nvim https://github.com/nvim-neorocks/rocks.nvim.git"
    "mutt-language-server https://github.com/neomutt/mutt-language-server.git"
    "delta https://github.com/dandavison/delta.git"
    "pest-ide-tools https://github.com/pest-parser/pest-ide-tools.git"
    "visidata https://github.com/saulpw/visidata.git"
    "oxc https://github.com/oxc-project/oxc.git"
    "pascal-language-server https://github.com/genericptr/pascal-language-server.git"
    "mdBook https://github.com/rust-lang/mdBook.git"
    "base16-builder-go https://github.com/tinted-theming/base16-builder-go.git"
    "CMake https://github.com/Kitware/CMake.git"
    "swig https://github.com/swig/swig.git"
    "tinytex https://github.com/yihui/tinytex.git"
    "nvim-idris2 https://github.com/ShinKage/nvim-idris2.git"
    "luau-lsp https://github.com/JohnnyMorganz/luau-lsp.git"
    "bats-mock https://github.com/buildkite-plugins/bats-mock.git"
    "bat https://github.com/sharkdp/bat.git"
    "ipython https://github.com/ipython/ipython.git"
    "direnv https://github.com/direnv/direnv.git"
    "autotools-language-server https://github.com/Freed-Wu/autotools-language-server.git"
    "jupyterlab_sublime https://github.com/zhangfeiran/jupyterlab_sublime.git"
    "numd https://github.com/nushell-prophet/numd.git"
    "PK-Py https://github.com/peytoncchen/PK-Py.git"
    "hydra-lsp https://github.com/Retsediv/hydra-lsp.git"
    "ipykernel https://github.com/ipython/ipykernel.git"
    "gocc https://github.com/goccmack/gocc.git"
    "asm-lsp https://github.com/bergercookie/asm-lsp.git"
    "fidget.nvim https://github.com/j-hui/fidget.nvim.git"
    "WoeUSB-ng https://github.com/WoeUSB/WoeUSB-ng.git"
    "generate_install_command https://github.com/Epineph/generate_install_command.git"
    "jupyterlab-lsp https://github.com/jupyter-lsp/jupyterlab-lsp.git"
    "MoBi https://github.com/Open-Systems-Pharmacology/MoBi.git"
    "sphinx https://github.com/sphinx-doc/sphinx.git"
    "mdbook-latex https://github.com/lbeckman314/mdbook-latex.git"
    "rust-csv https://github.com/BurntSushi/rust-csv.git"
    "bash-language-server https://github.com/bash-lsp/bash-language-server.git"
    "crowbook https://github.com/lise-henry/crowbook.git"
    "portable https://github.com/libressl-portable/portable.git"
    "beautysh https://github.com/lovesegfault/beautysh.git"
    "vim-lsp https://github.com/prabirshrestha/vim-lsp.git"
    "carapace-bin https://github.com/carapace-sh/carapace-bin.git"
    "my_R_config https://github.com/Epineph/my_R_config.git"
    "mdcat https://github.com/swsnr/mdcat.git"
    "quarto-cli https://github.com/quarto-dev/quarto-cli.git"
    "package_control https://github.com/wbond/package_control.git"
    "zoxide https://github.com/ajeetdsouza/zoxide.git"
    "bats-core https://github.com/bats-core/bats-core.git"
    "rdkit https://github.com/rdkit/rdkit.git"
    "sublime https://github.com/JaredCubilla/sublime.git"
    "eza-themes https://github.com/eza-community/eza-themes.git"
    "dracula.nvim https://github.com/Mofiqul/dracula.nvim.git"
    "mason-registry https://github.com//mason-org/mason-registry.git"
    "nvim-dap https://github.com/mfussenegger/nvim-dap.git"
    "move https://github.com/move-language/move.git"
    "MathJax-demos-node https://github.com/mathjax/MathJax-demos-node.git"
    "vdplus https://github.com/visidata/vdplus.git"
    "papaja https://github.com/crsh/papaja.git"
    "nelua.vim https://github.com/stefanos82/nelua.vim.git"
    "Arch-Hyprland https://github.com/JaKooLit/Arch-Hyprland.git"
    "jsoncpp https://github.com/open-source-parsers/jsoncpp.git"
    "jupyter_client https://github.com/jupyter/jupyter_client.git"
    "markdown https://github.com/Python-Markdown/markdown.git"
    "lsd https://github.com/lsd-rs/lsd.git"
    "bats-support https://github.com/bats-core/bats-support.git"
    "mdbook-preprocessor-utils https://github.com/willcrichton/mdbook-preprocessor-utils.git"
    "OSPSuite-R https://github.com/Open-Systems-Pharmacology/OSPSuite-R.git"
    "ryacas https://github.com/r-cas/ryacas.git"
    "ipynb-to-md https://github.com/diaakasem/ipynb-to-md.git"
    "PerlNavigator https://github.com/bscan/PerlNavigator.git"
    "nteract https://github.com/nteract/nteract.git"
    "jupyter_core https://github.com/jupyter/jupyter_core.git"
    "qtconsole https://github.com/jupyter/qtconsole.git"
    "bat-extras https://github.com/eth-p/bat-extras.git"
    "fancybook https://github.com/drahnr/fancybook.git"
    "alacritty https://github.com/alacritty/alacritty.git"
    "openscad-language-server https://github.com/dzhu/openscad-language-server.git"
    "doxygen https://github.com/doxygen/doxygen.git"
    "Packages https://github.com/sublimehq/Packages.git"
    "plotpy https://github.com/cpmech/plotpy.git"
    "networkx https://github.com/networkx/networkx.git"
    "ipyflex https://github.com/trungleduc/ipyflex.git"
    "lazygit https://github.com/jesseduffield/lazygit.git"
    "nickel https://github.com/tweag/nickel.git"
    "next-ls https://github.com/elixir-tools/next-ls.git"
    "slather https://github.com/SlatherOrg/slather.git"
    "base16-shell https://github.com/chriskempson/base16-shell.git"
    "sh-to-markdown https://github.com/rreinold/sh-to-markdown.git"
    "bats-file https://github.com/bats-core/bats-file.git"
    "NvChad https://github.com/NvChad/NvChad.git"
    "nimlsp https://github.com/PMunch/nimlsp.git"
    "fd https://github.com/sharkdp/fd.git"
    "openbabel https://github.com/openbabel/openbabel.git"
    "markdown-it https://github.com/markdown-it/markdown-it.git"
    "rmarkdown https://github.com/rstudio/rmarkdown.git"
    "mdbook-katex https://github.com/lzanini/mdbook-katex.git"
    "schemes https://github.com/tinted-theming/schemes.git"
    "ninja https://github.com/ninja-build/ninja.git"
    "python-lsp-black https://github.com/python-lsp/python-lsp-black.git"
    "sublime-bats https://github.com/sptndc/sublime-bats.git"
    "numpy https://github.com/numpy/numpy.git"
    "pharmsol https://github.com/LAPKB/pharmsol.git"
    "rich-cli https://github.com/Textualize/rich-cli.git"
    "flavours https://github.com/Misterio77/flavours.git"
    "miller https://github.com/johnkerl/miller.git"
    "MathJax-docs https://github.com/mathjax/MathJax-docs.git"
    "htmx-lsp https://github.com/ThePrimeagen/htmx-lsp.git"
    "linkify-it https://github.com/markdown-it/linkify-it.git"
    "prettier https://github.com/prettier/prettier.git"
    "chainer-chemistry https://github.com/chainer/chainer-chemistry.git"
    "ipywidgets https://github.com/jupyter-widgets/ipywidgets.git"
    "vcpkg https://github.com/microsoft/vcpkg.git"
    "processing-sublime https://github.com/b-g/processing-sublime.git"
    "magic-wormhole https://github.com/magic-wormhole/magic-wormhole.git"
    "SublimeAllAutocomplete https://github.com/alienhard/SublimeAllAutocomplete.git"
    "semver https://github.com/semver/semver.git"
    "awk-language-server https://github.com/Beaglefoot/awk-language-server.git"
    "mulle-bashfunctions https://github.com/mulle-nat/mulle-bashfunctions.git"
    "xcbuild https://github.com/facebook/xcbuild.git"
    "rich https://github.com/Textualize/rich.git"
    "zfsArch https://github.com/Epineph/zfsArch.git"
    "nvim-jdtls https://github.com/mfussenegger/nvim-jdtls.git"
    "nvim_conf https://github.com/Epineph/nvim_conf.git"
    "openscad-LSP https://github.com/Leathong/openscad-LSP.git"
    "backup_scripts https://github.com/Epineph/backup_scripts.git"
    "etc_jupyterlab_nbgrader_validate https://github.com/educational-technology-collective/etc_jupyterlab_nbgrader_validate.git"
    "tree-sitter-phpdoc https://github.com/claytonrcarter/tree-sitter-phpdoc.git"
    "re2c https://github.com/skvadrik/re2c.git"
    "RHash https://github.com/rhash/RHash.git"
    "tinted-shell https://github.com/tinted-theming/tinted-shell.git"
)
# Directory to store repositories
repo_dir="/home/heini/repos/"
mkdir -p "$repo_dir"

# Check and clone repositories if they do not exist
for repo in "${repos[@]}"; do
    name=$(echo "$repo" | cut -d ' ' -f 1)
    url=$(echo "$repo" | cut -d ' ' -f 2)
    path="$repo_dir/$name"

    if [ ! -d "$path" ]; then
        echo "Cloning $name from $url..."
        git clone --recurse-submodules "$url" "$path"
    else
        echo "$name already exists at $path."
    fi
done

